<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ck</name>
   <tag></tag>
   <elementGuidId>45074934-1dee-48c9-840b-5c679257d40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>cke_1_contents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cke_1_contents&quot;]/iframe</value>
   </webElementProperties>
</WebElementEntity>
